### ISSUE TITLE
Lacks model.zip

### ISSUE THREAD

**Issue by jianwang-mpi** [MandyMo/pytorch_HMR#1]
You mentioned that in order to train the model, model.zip should be unzipped. However, I cannot find model.zip in your repo. Could you please upload it as soon as possible? Thanks.

**Comment by MandyMo** [comment]
I am sorry for this mistake, I have upload the model.zip just now, please read the .md file and download it.

If you have google drive, you can upload all the resource on it.

**Comment by jianwang-mpi** [comment]
Another problem:
Pre-trained model is needed in config.py, however I cannot see it in the repo. Is it not added to repo either?

**Comment by MandyMo** [comment]
You can train hmr from scratch.
