### ISSUE TITLE
How did you calculate parameters of Human3.6M ?

### ISSUE THREAD

**Issue by gsygsy96** [MandyMo/pytorch_HMR#10]
Human 3.6M didn't provide SMPL parameter. Could you explain how to calculate groundtruth parameter?

**Comment by MandyMo** [comment]
I am sorry, I just covert the TF records that given by the authors to images and labels.

**Comment by liwenssss** [comment]
@MandyMo ,hi can you share the TF records? I cant get the data anywhere.

**Comment by JackSyu** [comment]
@shyanguan  Hi, did you get access of h36m Mosh result? If you did, could you tell me how to get it? For example, contact the author of Mosh? Thank you very much.
