### ISSUE TITLE
Is there an already trained model ? 

### ISSUE THREAD

**Issue by MoMe36** [MandyMo/pytorch_HMR#11]
Hello, 

I'd like to use HMR for a personal project. Would you happen to have a trained model or do I have to put my GPU to work ? ;) 

Thanks !

**Comment by MandyMo** [comment]
Please leave me your email, I will send it to you.

**Comment by MoMe36** [comment]
mehdi.mounsif@uca.fr

Thanks a lot !

**Comment by chingswy** [comment]
Could you share a pre-trained model for me? s_q@zju.edu.cn, thanks!

**Comment by l1346792580123** [comment]
762373701@qq.com 如果可以的话也给我发一份  谢谢

**Comment by tszhang97** [comment]
z501812442@163.com 
thanks a lot!!!

**Comment by StevenLiuWen** [comment]
liuwen@shanghaitech.edu.cn
interesting work, thanks a lot!!!

**Comment by Dene33** [comment]
den33.info@gmail.com would like to have pre-trained model as well. Thanks.

**Comment by nicolasugrinovic** [comment]
Hi, 
Could you send me the pre-trained model, please. Thank you!
nicolas.ugrinovic.k@gmail.com

**Comment by wangsen1312** [comment]
Could you share a pre-trained model for me?  wangsen1312@gmail.com 
thanks!

**Comment by intvo** [comment]
Hello 
Could you share a pre-trained model for me? aalzooke@gmail.com

**Comment by hshustc** [comment]
Hi, could you please also share a pre-trained model for me? My email is hshsmile@126.com.

**Comment by hsyntemiz** [comment]
Could you share a pre-trained model for me? hsyntemiz@yahoo.com

**Comment by lxy5513** [comment]
@MandyMo   
Hi   
Could you please share me a pre-trained model, my email is lxy5513@gmial.com   
Thank you a lot!

**Comment by hsyntemiz** [comment]
I trained the model 100K iterations, but does not gives good results.  I want to check my results with a well-trained model.

**Comment by hsyntemiz** [comment]
I wonder how many iterations model need while training (default config 500K) ? Please,, share your training experience. Can anyone get good result with own trained models?

**Comment by AdrienBenamira** [comment]
Hello @MandyMo 

Thanks a lot for your work ! Could you please share me a pre-trained model, my email is techno.abenamira@gmail.com

Thank you again and happy new year

**Comment by lyokka** [comment]
Hello @MandyMo 

Could you please share me a pre-trained model, 1185018266@qq.com
Thank you very much !

**Comment by OptimusPrimeCao** [comment]
Hello @MandyMo

Could you please share me a pre-trained model, 1026843483@qq.com
Thank you very much !

**Comment by rohitrango** [comment]
Hello @mandymo

Can you please share the pretrained model with me? I need it for a project. My email is rohitrango@cse.iitb.ac.in

Thank you

**Comment by twister726** [comment]
Hello @MandyMo 

Can you please share the pretrained model with me? I was unable to download it from Baidu, and need it for my research work. My email is sourabh.rajguru@students.iiit.ac.in

Thank You.

**Comment by tszhang97** [comment]
I‘ve trained this with 40000iterations, if anyone want a pretrained-model(generator.pkl,discriminator.pkl), please email me z501812442@163.com.

**Comment by bestsunlin** [comment]
How about the performance? @willie1997

**Comment by KevinCHow1020** [comment]
631553646@qq.com
如果方便的话，也请发一份给我可以吗，谢谢啦！

**Comment by ah651** [comment]
Hello @MandyMo

Can you please share the pretrained model with me? I cann't download some training datasets. My email is 1150310212@stu.hit.edu.cn

Thank You.

**Comment by Vegetebird** [comment]
Hello 
Could you please share me a pre-trained model, 781256005@qq.com
Thank you very much

**Comment by aolle125** [comment]
Hello @MandyMo 

I was not able to download some of the datasets, so would it be possible for you to share the pretrained model?
My email is pradaofficial25@gmail.com

Thank you.

**Comment by qaz123321qaz** [comment]
Hello @MandyMo 
My email is 312280234@qq.com
Can you give me the pretrained model
Thank you

**Comment by fmx789** [comment]
Hello @MandyMo
Can you please share the pretrained model with me? 
My email is [793414991@qq.com](mailto:793414991@qq.com)
Thank you!

**Comment by Su-yukun** [comment]
> 你好，
> 
> 我想将 HMR 用于个人项目。您是否有经过训练的模型，还是我必须使用 GPU 来工作？;)
> 
> 谢谢 ！

Hello, I would like to inquire if you still have the trained models from the project https://github.com/MandyMo/pytorch_HMR that were sent to you, especially the discriminator models. My personal project requires their use, but unfortunately, I have not been able to find them on GitHub. If you still have them, I would greatly appreciate it if you could share them with me. Thank you.
