### ISSUE TITLE
Access to files and pretrained models

### ISSUE THREAD

**Issue by AdityaAS** [MandyMo/pytorch_HMR#14]
Hi @MandyMo,

Could you please upload all the files in google drive / dropbox?

In order to create a Baidu account - to download the files, a chinese mobile number is needed which I don't have.

**Comment by MandyMo** [comment]
I am considering, thank you for you suggestion.

**Comment by AdityaAS** [comment]
@MandyMo thanks. Would really appreciate if you could upload them soon

**Comment by Dawars** [comment]
@AdityaAS I used this extension with the RPC method with great success:
https://github.com/Kyle-Kyle/baidudl/

**Comment by AdityaAS** [comment]
@Dawars @MandyMo The extension still needs me to have a Baidu account - but I do not have a Chinese phone number. Is there a workaround?

**Comment by Dawars** [comment]
@AdityaAS No, you don't need one, it'll generate a link for you

**Comment by AdrienBenamira** [comment]
@Dawars  @AdityaAS  @MandyMo 

Hello all, Like @AdityaAS I could not get the pretrained model. Can you provided an other way, like google drive or sent it by mail ?

Thank you !

**Comment by Su-yukun** [comment]
> @AdityaAS我使用这个扩展和 RPC 方法取得了巨大的成功： https://github.com/Kyle-Kyle/baidudl/

Hello, I would like to inquire if you still have the trained models from the project https://github.com/MandyMo/pytorch_HMR that were sent to you, especially the discriminator models. My personal project requires their use, but unfortunately, I have not been able to find them on GitHub. If you still have them, I would greatly appreciate it if you could share them with me. Thank you.
