### ISSUE TITLE
camera parameters for human3.6m

### ISSUE THREAD

**Issue by kalyo-zjl** [MandyMo/pytorch_HMR#16]
Hi, could you please share some extra data like camera parameters (focal length, principal pt) and translation vector so that I can render the human3.6m 3D model to the corresponding images. Thanks.

**Comment by MandyMo** [comment]
First, you should crop the people out from the image, then regression of the camera parameters (translation, scale) as well as the smpl parameters (theta, beta).

Under the premise of given those parameters, your can render the SMPL model to a image(maybe 224 x 224), then resize and translate the rendered image to make it fit the original image.

**Comment by kalyo-zjl** [comment]
@MandyMo  Yeah, I know that I can regress the parameters manually. But since you already have shared the smpl parameters in hum3.6m_anno.zip, do you have the corresponding camera parameters?
