### ISSUE TITLE
Missing smpl's parameter

### ISSUE THREAD

**Issue by Hummmm** [MandyMo/pytorch_HMR#17]
HI,
I want to run a demo.py to test trained model. However, the result turns out like this,
"finished create the encoder modules...
parameter smpl.v_template not found
parameter smpl.shapedirs not found
parameter smpl.J_regressor not found
parameter smpl.posedirs not found
parameter smpl.joint_regressor not found
parameter smpl.weight not found
parameter smpl.e3 not found"
Did I miss any code as I only use"smpl = model.smpl" ?

**Comment by MandyMo** [comment]
These parameters are constant, as a result, they are not included in the pre-trained model.
