### ISSUE TITLE
What is the 'shape' and 'pose' keyword in the human36m annot.h5 file? The human 36m dataset doesn't have any 'shape' or 'pose' annotations.

### ISSUE THREAD

**Issue by hammad001** [MandyMo/pytorch_HMR#18]

**Comment by MandyMo** [comment]
Good question.

These label are man made by Michael.J.Black.
Still, I don't understand how they did it.

**Comment by weigq** [comment]
你好，请问Human36m的这些label有相关的网页或者论文吗？

**Comment by JackSyu** [comment]
@weigq 请问您现在找到h36m的mosh data了么，或者有什么途径可以获取到，谢谢

**Comment by zhaiyukun** [comment]
@JackSyu 请问您找到了么？
