### ISSUE TITLE
Cannot download files

### ISSUE THREAD

**Issue by rohitrango** [MandyMo/pytorch_HMR#19]
Hi,

I cannot seem to download the baidu files. I even tried the chrome extension. Is there a workaround?

**Comment by twister726** [comment]
I also am facing the same issue and would greatly appreciate alternate download links.

**Comment by MandyMo** [comment]
Recently, I am busy, but these datas will available at Google Drive at the near future.

**Comment by ryoppippi** [comment]
Hi
Could you upload the models data on GD?

**Comment by bala1144** [comment]
Hi
Thanks for the implementation.
It would be great if you can share the pre trained model ?
