### ISSUE TITLE
process scripts of datasets

### ISSUE THREAD

**Issue by lyupei** [MandyMo/pytorch_HMR#2]
Hi,

would you like to offer the process scripts of datasets?

downloading the datasets from Baidu Netdisk is much too slow

**Comment by MandyMo** [comment]
I am sorry, I use the same python script with the original paper (the author offered the script) except that I have saved all the label in a h5 file.

**Comment by MandyMo** [comment]
The original paper offered the tf-record, also you can parse it directly.

**Comment by lyupei** [comment]
ok，thanks

**Comment by nicolasugrinovic** [comment]
Hi, 
Could you send me the .h5 files that you use. I have tried to use Baidu, but could not load. I have created an account, but I cannot download with that either. My mail is nicolas.ugrinovic.k@gmail.com
Thank you in advanced!
