### ISSUE TITLE
Could you share the data again?

### ISSUE THREAD

**Issue by wkqscut** [MandyMo/pytorch_HMR#21]
The data link you provided seems to have expired. Could you please share it again? Thanks a lot.

**Comment by MandyMo** [comment]
I am sorry, I can not share the benchmarks as mentioned above publicly because of license limitation.

**Comment by 124518** [comment]
@MandyMo 您好，可以分享一下Mosh数据吗，我的邮箱是1245525304@qq.com.非常感谢！
