### ISSUE TITLE
Can't download human36m dataset

### ISSUE THREAD

**Issue by zhou07** [MandyMo/pytorch_HMR#26]
I can't download human36m dataset by the link you provided, and the official website is too damn slow. So can you provide the link again?

**Comment by MandyMo** [comment]
I am sorry, I can not share the links publicly due to license limitation.

**Comment by zhou07** [comment]
OK. Thank you! But can you share human36m dataset with me by other methods privately?


------------------ 原始邮件 ------------------
发件人: "zhang xiong"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 下午3:30
收件人: "MandyMo/pytorch_HMR"<pytorch_HMR@noreply.github.com>;
抄送: "周蕾"<1586674111@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MandyMo/pytorch_HMR] Can't download human36m dataset (#26)




I am sorry, I can not share the links publicly due to license limitation.

**Comment by MandyMo** [comment]
你可以找我来拿U盘拷.

**Comment by zhou07** [comment]
emmmm，，，，这大约是有点难度吧，邮件发送一下可以么？




------------------ 原始邮件 ------------------
发件人: "zhang xiong"<notifications@github.com>;
发送时间: 2019年4月19日(星期五) 下午5:24
收件人: "MandyMo/pytorch_HMR"<pytorch_HMR@noreply.github.com>;
抄送: "周蕾"<1586674111@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MandyMo/pytorch_HMR] Can't download human36m dataset (#26)




你可以找我来拿U盘拷.

**Comment by hello-world-zsp** [comment]
同求h3.6m数据。
之前在您这下到过，现在缺失了part2。你在北京的话可以找你拷一下吗？能邮件最好了。拜谢。

**Comment by zhou07** [comment]
你好！
请问你现在有h3.6m数据么？跪求




------------------ 原始邮件 ------------------
发件人: "hello-world-zsp"<notifications@github.com>;
发送时间: 2019年4月26日(星期五) 下午5:23
收件人: "MandyMo/pytorch_HMR"<pytorch_HMR@noreply.github.com>;
抄送: "周蕾"<1586674111@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [MandyMo/pytorch_HMR] Can't download human36m dataset (#26)




同求h3.6m数据。
 之前在您这下到过，现在缺失了part2。你在北京的话可以找你拷一下吗？能邮件最好了。拜谢。

**Comment by benjiebob** [comment]
I also need the h3.6m data. Is there some other place we can download this? Or would anyone be kind enough to provide?

**Comment by jinx-USTC** [comment]
> 同求h3.6m数据。
> 之前在您这下到过，现在缺失了part2。你在北京的话可以找你拷一下吗？能邮件最好了。拜谢。

你好，请问您下载到3.6m数据集了吗，如果能分享一下就太感谢了，可以私信聊，感谢感谢，18829037099@163.com

**Comment by yifengji** [comment]
> emmmm，，，，这大约是有点难度吧，邮件发送一下可以么？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "zhang xiong"<notifications@github.com>; 发送时间: 2019年4月19日(星期五) 下午5:24 收件人: "MandyMo/pytorch_HMR"<pytorch_HMR@noreply.github.com>; 抄送: "周蕾"<1586674111@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [MandyMo/pytorch_HMR] Can't download human36m dataset (#26) 你可以找我来拿U盘拷. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.



> 同求h3.6m数据。
> 之前在您这下到过，现在缺失了part2。你在北京的话可以找你拷一下吗？能邮件最好了。拜谢。

你能分享一下给我么？求。谢谢了

**Comment by MandyMo** [comment]
I am sorry, I cannot share the data due to the license limitation.

**Comment by ah651** [comment]
> emmmm，，，，这大约是有点难度吧，邮件发送一下可以么？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "zhang xiong"<notifications@github.com>; 发送时间: 2019年4月19日(星期五) 下午5:24 收件人: "MandyMo/pytorch_HMR"<pytorch_HMR@noreply.github.com>; 抄送: "周蕾"<1586674111@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [MandyMo/pytorch_HMR] Can't download human36m dataset (#26) 你可以找我来拿U盘拷. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

话说你现在有human3.6m数据集了吗？如果你有的话能否分享一下，非常感谢
