### ISSUE TITLE
Can you share the human3.6m moshed parameters?

### ISSUE THREAD

**Issue by bebory** [MandyMo/pytorch_HMR#33]
Hi, I am interested in the 3D reconstruction of human body. Can you share the human3.6m moshed data, like shapes and poses? Thank you very much!

**Comment by hongsukchoi** [comment]
I would also appreciate it!

**Comment by Karol-Perec** [comment]
Hey! I would also appreciate for sharing!

**Comment by bebory** [comment]
I found that this data cannot be shared, so I close this issue.
