### ISSUE TITLE
Could you share your test code?

### ISSUE THREAD

**Issue by gsygsy96** [MandyMo/pytorch_HMR#4]
Thanks for your reproduce! I also try to reproduce another work --- estimate human shape from only one color figure. Some part is similar to HMR. If you can share your test code, that will be a great apreciate!

**Comment by MandyMo** [comment]
https://github.com/MandyMo/pytorch_HMR/issues/3

**Comment by gsygsy96** [comment]
Another question, have your project 3d joints from world to camera coordiate?
