### ISSUE TITLE
训练并不收敛

### ISSUE THREAD

**Issue by lvZic** [MandyMo/pytorch_HMR#40]
你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。
是训练需要哪些trick吗？
还是要预训练，还是分两个网络分别训练吗？

**Comment by Qusong1** [comment]
> 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了

**Comment by lvZic** [comment]
> > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
都是开源的 自己下载吧

**Comment by Qusong1** [comment]
> > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > 都是开源的 自己下载吧

你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗

**Comment by Qusong1** [comment]
> > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > 都是开源的 自己下载吧

![image](https://github.com/MandyMo/pytorch_HMR/assets/102896917/9f169783-553e-4822-8da6-993a56e28634)

**Comment by lvZic** [comment]
> > > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > > 都是开源的 自己下载吧
> 
> 你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗

![image](https://github.com/MandyMo/pytorch_HMR/assets/7788572/1a2e87c0-9d9d-49ab-90e3-05df09bb9549)
他这里的链接我没用过 我是自己训练的 数据是从网上下载的

**Comment by Qusong1** [comment]
就是用的他分享的代码吗？那可以给个联系方式吗？遇到问题可以请教您，谢谢了

**Comment by Qusong1** [comment]
> > > > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > > > 都是开源的 自己下载吧
> > 
> > 
> > 你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗
> 
> ![image](https://user-images.githubusercontent.com/7788572/241632000-1a2e87c0-9d9d-49ab-90e3-05df09bb9549.png) 他这里的链接我没用过 我是自己训练的 数据是从网上下载的

就是用的他分享的代码吗？那可以给个联系方式吗？遇到问题可以请教您，谢谢了

**Comment by Asteria0000** [comment]
最终的训练效果如何？

**Comment by Qusong1** [comment]
> > > > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > > > 都是开源的 自己下载吧
> > 
> > 
> > 你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗
> 
> ![image](https://user-images.githubusercontent.com/7788572/241632000-1a2e87c0-9d9d-49ab-90e3-05df09bb9549.png) 他这里的链接我没用过 我是自己训练的 数据是从网上下载的

你好，这个代码训练完评估时需要用到tf_records_human36M dataset ，你有这个数据集的文件吗，如果有的话可以给我一份吗？谢谢啦

**Comment by Asteria0000** [comment]
> > > > > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > > > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > > > > 都是开源的 自己下载吧
> > > 
> > > 
> > > 你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/7788572/241632000-1a2e87c0-9d9d-49ab-90e3-05df09bb9549.png) 他这里的链接我没用过 我是自己训练的 数据是从网上下载的
> 
> 你好，这个代码训练完评估时需要用到tf_records_human36M dataset ，你有这个数据集的文件吗，如果有的话可以给我一份吗？谢谢啦

不好意思，我也没有

**Comment by Qusong1** [comment]
> > > > > > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > > > > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > > > > > 都是开源的 自己下载吧
> > > > 
> > > > 
> > > > 你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/7788572/241632000-1a2e87c0-9d9d-49ab-90e3-05df09bb9549.png) 他这里的链接我没用过 我是自己训练的 数据是从网上下载的
> > 
> > 
> > 你好，这个代码训练完评估时需要用到tf_records_human36M dataset ，你有这个数据集的文件吗，如果有的话可以给我一份吗？谢谢啦
> 
> 不好意思，我也没有

好的，谢谢

**Comment by Asteria0000** [comment]
> > > > > > > > 你好，我用hmr网络训练hand reconstruct任务，freihand数据集，回归cam参数+MANO参数，但是cam参数并不收敛，尤其是scale，基本不下降。 是训练需要哪些trick吗？ 还是要预训练，还是分两个网络分别训练吗？
> > > > > > > > 你好，这个版本的训练数据集与模型好像都已经过期了，你可以分享给我吗？我的QQ号是： 1849535352，谢谢了
> > > > > > > > 都是开源的 自己下载吧
> > > > > 
> > > > > 
> > > > > 你好，但是我根据给的链接点进去显示分享的文件已经失效了，请问您有备份吗
> > > > 
> > > > 
> > > > ![image](https://user-images.githubusercontent.com/7788572/241632000-1a2e87c0-9d9d-49ab-90e3-05df09bb9549.png) 他这里的链接我没用过 我是自己训练的 数据是从网上下载的
> > > 
> > > 
> > > 你好，这个代码训练完评估时需要用到tf_records_human36M dataset ，你有这个数据集的文件吗，如果有的话可以给我一份吗？谢谢啦
> > 
> > 
> > 不好意思，我也没有
> 
> 好的，谢谢

他的human3.6m好像是有smpl的shape和pose参数的，很离谱，我师兄说这可能是假标签，是用类似hmr方法生成的，我这里有一个coco带smpl参数的标签，就很离谱
