### ISSUE TITLE
Where is the global rotation of R referring to the paper？

### ISSUE THREAD

**Issue by Superlee506** [MandyMo/pytorch_HMR#6]
Hi, in the paper, I find the the parameters contains global rotation R (3x3), however I can't find it in the code. Do I miss something?
![image](https://user-images.githubusercontent.com/13114675/45533950-fe0a6a00-b82b-11e8-8e90-59f4851eceae.png)

**Comment by MandyMo** [comment]
I think you should have some knowledge about skinned animation.

**Comment by MandyMo** [comment]
SMPL has 24 x 3 + 10 parameters, 24 is 23 + 1, the 1 is the root rotation, which is the Theta given in the paper.
