### ISSUE TITLE
Which Python version?

### ISSUE THREAD

**Issue by Dawars** [MandyMo/pytorch_HMR#8]
Which Python version did you use?

I'm getting an error for trainer.py  line 302
```
  for iter_index in range(config.args.iter_count):
            try:
                data_2d = loader_2d.next() # <-
```
next is a built-in function from python 3 and should be called `next(loader_2d)`

And with Python 2.7 I get an error for copying a list in COCO2017_dataloader.py at line 117

`self.boxs.append(box.copy())`

This feature is only from Python 3.5

**Comment by Dawars** [comment]
I solved it by replacing next() as described above and ran with python3 pytorch 0.4.1

**Comment by MandyMo** [comment]
thank you.

Python 3.6 & Pytorch 0.4.0 were used in these code.
